package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFF6699)
val md_theme_light_onPrimary = Color(0xFFFFECF1)
val md_theme_light_primaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onPrimaryContainer = Color(0xFF3F001A)
val md_theme_light_secondary = Color(0xFFFF8CB0)
val md_theme_light_onSecondary = Color(0xFFFFB3CA)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onSecondaryContainer = Color(0xFF3F001C)
val md_theme_light_tertiary = Color(0xFFB21E5D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onTertiaryContainer = Color(0xFF3F001B)
val md_theme_light_error = Color(0xFFE84B85)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFECF1)
val md_theme_light_onBackground = Color(0xFF3E0021)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF3E0021)
val md_theme_light_surfaceVariant = Color(0xFFF3DDE1)
val md_theme_light_onSurfaceVariant = Color(0xFF514346)
val md_theme_light_outline = Color(0xFF847376)
val md_theme_light_inverseOnSurface = Color(0xFFFFECF0)
val md_theme_light_inverseSurface = Color(0xFF5D1137)
val md_theme_light_inversePrimary = Color(0xFFFFB1C5)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFAF265C)
val md_theme_light_outlineVariant = Color(0xFFD6C2C5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB1C5)
val md_theme_dark_onPrimary = Color(0xFF65002F)
val md_theme_dark_primaryContainer = Color(0xFF8E0344)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_secondary = Color(0xFFFFB1C6)
val md_theme_dark_onSecondary = Color(0xFF610B31)
val md_theme_dark_secondaryContainer = Color(0xFF7E2547)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_tertiary = Color(0xFFFFB1C5)
val md_theme_dark_onTertiary = Color(0xFF650030)
val md_theme_dark_tertiaryContainer = Color(0xFF8F0046)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF3E0021)
val md_theme_dark_onBackground = Color(0xFFFFD9E4)
val md_theme_dark_surface = Color(0xFF3E0021)
val md_theme_dark_onSurface = Color(0xFFFFD9E4)
val md_theme_dark_surfaceVariant = Color(0xFF514346)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C2C5)
val md_theme_dark_outline = Color(0xFF9E8C8F)
val md_theme_dark_inverseOnSurface = Color(0xFF3E0021)
val md_theme_dark_inverseSurface = Color(0xFFFFD9E4)
val md_theme_dark_inversePrimary = Color(0xFFAF265C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB1C5)
val md_theme_dark_outlineVariant = Color(0xFF514346)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFF6699)
